; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "BioSync"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Right iTech"
#define MyAppURL "https://github.com/ramimrbx/biosync"
#define MyAppExeName "BioSync.exe"
#define MyBuildDir "C:\Users\ramim\Projects\Software\biosync\cmake-build-release"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{7A880B11-3DDF-4EEC-997E-13591EA773AB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}

ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

DisableProgramGroupPage=yes
OutputDir=C:\Users\ramim\Projects\Software\biosync\installer\windows
OutputBaseFilename=BioSync_Setup_v{#MyAppVersion}

SetupIconFile=C:\Users\ramim\Projects\Software\biosync\src\assets\images\icon.ico

Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startupicon"; Description: "Start BioSync automatically when Windows starts (recommended)"; GroupDescription: "Startup:"

[Files]
; Ship the whole deployed build tree (Qt DLLs, plugin folders, MinGW runtime), but
; exclude the CMake/Ninja build artifacts that live alongside it in the build dir.
Source: "{#MyBuildDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "CMakeFiles,BioSync_autogen,.qt,CMakeCache.txt,cmake_install.cmake,*.ninja,.ninja_deps,.ninja_log,*.cbp,*.a,*.o"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; Launch BioSync at Windows startup so the attendance server is always running. Per-user Run key,
; so no administrator rights are needed at runtime; removed cleanly on uninstall.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "BioSync"; ValueData: """{app}\{#MyAppExeName}"""; Tasks: startupicon; Flags: uninsdeletevalue

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
